version: "3"
services:
  cloudflared:
    build:
      context: ./cloudflared
    restart: always
  dnsmasq:
    build:
      context: ./dnsmasq
    restart: always
    depends_on:
      - cloudflared
    ports:
      - "5300:53/udp"
  clash:
    build:
      context: ./clash
    volumes:
      - ./clash/config.yml:/.config/clash/config.yml:ro
    # ports is useless when network mode is host.
    ports:
      - "7890:7890"
      - "7891:7891"
      - "7892:7892"
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - dnsmasq