version: "3"
services:
  cloudflared:
    build:
      context: ./cloudflared
    restart: always
  dnsmasq:
    build:
      context: ./dnsmasq
    restart: always
    depends_on:
      - cloudflared
    ports:
      - "5300:53/udp"