port: 7890
socks-port: 7891
redir-port: 7892

# `allow-lan` must be true in your config.yml
allow-lan: false
mode: Rule
external-controller: 0.0.0.0:8080

log-level: info

# Config file example: https://github.com/Dreamacro/clash
